mysql:
  regex: "mysql"
  image: "mysql:latest"
  commands:
    {% if env.MYSQL_USER and env.MYSQL_DATABASE %}
    {# When user, password and database setted #}
    - "sh -c 'mysqldump -h {{ ip }} -u {{ env.MYSQL_USER }} {{env.MYSQL_DATABASE}} > {{ target_dir }}/{{ env.MYSQL_DATABASE }}.dump'"

    {% elif env.MYSQL_USER and not env.MYSQL_DATABASE %}
    {# When user, password setted #}
    - "sh -c 'mysqldump -h {{ ip }} -u {{ env.MYSQL_USER }} --all-databases > {{ target_dir }}/all-databases.dump'"

    {% elif not env.MYSQL_USER and env.MYSQL_DATABASE %}
    {# When database setted #}
    - "sh -c 'mysqldump -h {{ ip }} -u root {{env.MYSQL_DATABASE}} > {{ target_dir }}/{{ env.MYSQL_DATABASE }}.dump'"

    {% elif not env.MYSQL_USER and not env.MYSQL_DATABASE %}
    {# When just root setted #}
    - "sh -c 'mysqldump -h {{ ip }} -u root --all-databases > {{ target_dir }}/all-databases.dump'"

    {% endif %}
  environments:
    {% if env.MYSQL_PASSWORD %}
    - MYSQL_PWD:{{ env.MYSQL_PASSWORD }}
    {% elif env.MYSQL_ROOT_PASSWORD %}
    - MYSQL_PWD:{{ env.MYSQL_ROOT_PASSWORD }}
    {% endif %}
